# Build AirQI App

name: AirQI App Builder

on:
  push:
    branches: 
      - main
    paths:
      - "AirQIApp/**"
  pull_request:
    branches: 
      - main
    paths:
      - "AirQIApp/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout 
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      working-directory: AirQIApp
      run: |
        npm ci
        npm run build --if-present
