# Compile Node MCU esp8266 code

name: Node MCU Code Builder

on:
  push:
    branches: 
      - main
    paths:
      - "NodeMCUCode/**"
  pull_request:
    branches: 
      - main
    paths:
      - "NodeMCUCode/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Compile ESP8266 Code
        uses: arduino/compile-sketches@v1
        with:
          fqbn:  "esp8266:esp8266:nodemcuv2:xtal=80,baud=115200"
          platforms: |
              - name: esp8266:esp8266
                source-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
                version: latest
          libraries: |
            - name: PubSubClient
            - name: WiFiManager
            - name: ArduinoJson
            - name: NTPClient
          sketch-paths: "- NodeMCUCode"
          verbose: true
