# Compile Node MCU esp8266 code

name: Node MCU Code Builder

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Compile ESP8266 Code
        uses: arduino/compile-sketches@v1
        with:
          platforms: |
            - name: "esp8266:esp8266"
          libraries: |
            - name: ESP8266WiFi
            - name: ESP8266WebServer
            - name: ESP8266mDNS
            - name: DNSServer
            - name: WiFiUdp
            - name: PubSubClient
            - name: WiFiManager
            - name: ArduinoJson
            - name: NTPClient
